package org.openrewrite

import java.net.URI
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardOpenOption
import org.openrewrite.RecipeMarkdownGenerator.Companion.useAndApply
import org.openrewrite.RecipeMarkdownGenerator.Companion.writeln

class VersionWriter {
    fun createLatestVersionsMarkdown(
        outputPath: Path,
        recipeOrigins: Collection<RecipeOrigin>,
        rewriteBomVersion: String,
        rewriteRecipeBomVersion: String,
        moderneRecipeBomVersion: String,
        gradlePluginVersion: String,
        mavenPluginVersion: String
    ) {
        val versionsSnippetPath = outputPath.resolve("latest-versions-of-every-openrewrite-module.md")
        Files.newBufferedWriter(versionsSnippetPath, StandardOpenOption.CREATE).useAndApply {
            val rewriteBomLink =
                "[${rewriteBomVersion}](https://github.com/openrewrite/rewrite/releases/tag/v${rewriteBomVersion})"
            val rewriteRecipeBomLink =
                "[${rewriteRecipeBomVersion}](https://github.com/openrewrite/rewrite-recipe-bom/releases/tag/v${rewriteRecipeBomVersion})"
            val moderneBomLink =
                "[${moderneRecipeBomVersion}](https://github.com/moderneinc/rewrite-recipe-bom/releases/tag/v${moderneRecipeBomVersion})"
            val mavenLink =
                "[${mavenPluginVersion}](https://github.com/openrewrite/rewrite-maven-plugin/releases/tag/v${mavenPluginVersion})"
            val gradleLink =
                "[${gradlePluginVersion}](https://github.com/openrewrite/rewrite-gradle-plugin/releases/tag/v${gradlePluginVersion})"

            //language=markdown
            writeln(
                """
                ---
                description: An autogenerated table with the latest version of each OpenRewrite module. Updates on an OpenRewrite release.
                ---

                import Tabs from '@theme/Tabs';
                import TabItem from '@theme/TabItem';

                # Latest versions of every OpenRewrite module

                OpenRewrite's modules are published to [Maven Central](https://search.maven.org/search?q=org.openrewrite).
                Each time a release is made, a bill of materials artifact is also published to correctly align and manage the versions of all published artifacts.
                The Gradle plugin is published to the [Gradle Plugin Portal](https://plugins.gradle.org/plugin/org.openrewrite.rewrite).

                It is highly recommended that developers use the [rewrite-recipe-bom](https://github.com/openrewrite/rewrite-recipe-bom)
                to align the versions of Rewrite's modules to ensure compatibility.
                The use of the "bill of materials" means that a developer will only need to specify explicit versions of the BOM and the build plugins:

                | Module                                                                                                                | Version    | License |
                |-----------------------------------------------------------------------------------------------------------------------| ---------- | ------- |
                | [**org.openrewrite:rewrite-bom**](https://github.com/openrewrite/rewrite)                                             | **${rewriteBomLink}** | ${Licenses.Apache2.markdown()} |
                | [**org.openrewrite:rewrite-maven-plugin**](https://github.com/openrewrite/rewrite-maven-plugin)                       | **${mavenLink}** | ${Licenses.Apache2.markdown()} |
                | [**org.openrewrite:rewrite-gradle-plugin**](https://github.com/openrewrite/rewrite-gradle-plugin)                     | **${gradleLink}** | ${Licenses.Apache2.markdown()} |
                | [**org.openrewrite.recipe:rewrite-recipe-bom**](https://github.com/openrewrite/rewrite-recipe-bom)                    | **${rewriteRecipeBomLink}** | ${Licenses.Apache2.markdown()} |
                | [**io.moderne.recipe:moderne-recipe-bom**](https://github.com/moderneinc/moderne-recipe-bom)                          | **${moderneBomLink}** | ${Licenses.Proprietary.markdown()} |
                """.trimIndent()
            )
            var cliInstallJarPinned = ""
            var cliInstallJarLatest = ""
            var cliInstallPipPinned = ""
            var cliInstallPipLatest = ""
            var cliInstallNpmPinned = ""
            var cliInstallNpmLatest = ""
            var cliInstallNugetPinned = ""
            var cliInstallNugetLatest = ""
            var cliInstallGoPinned = ""
            var cliInstallGoLatest = ""
            var installRecipes = ""
            for (origin in recipeOrigins) {

                val versionPlaceholder = "{{${origin.versionPlaceholderKey()}}}"
                when (origin.artifactId) {
                    in PythonRecipeLoader.PYTHON_RECIPE_MODULES -> {
                        val pipPackage = PythonRecipeLoader.PYTHON_RECIPE_MODULES.getValue(origin.artifactId)
                        cliInstallPipPinned += "$pipPackage==$versionPlaceholder "
                        cliInstallPipLatest += "$pipPackage "
                    }
                    in TypeScriptRecipeLoader.TYPESCRIPT_RECIPE_MODULES -> {
                        val npmPackage = TypeScriptRecipeLoader.TYPESCRIPT_RECIPE_MODULES.getValue(origin.artifactId)
                        cliInstallNpmPinned += "$npmPackage@$versionPlaceholder "
                        cliInstallNpmLatest += "$npmPackage "
                    }
                    in CSharpRecipeLoader.CSHARP_RECIPE_MODULES -> {
                        val nugetPackage = CSharpRecipeLoader.CSHARP_RECIPE_MODULES.getValue(origin.artifactId)
                        cliInstallNugetPinned += "$nugetPackage@$versionPlaceholder "
                        cliInstallNugetLatest += "$nugetPackage "
                    }
                    in GoRecipeLoader.GO_RECIPE_MODULES -> {
                        // Go modules are installed from source by module path, pinned with a vX.Y.Z tag.
                        val goModule = GoRecipeLoader.GO_RECIPE_MODULES.getValue(origin.artifactId)
                        cliInstallGoPinned += "$goModule@v$versionPlaceholder "
                        cliInstallGoLatest += "$goModule "
                    }
                    else -> {
                        cliInstallJarPinned += "${origin.groupId}:${origin.artifactId}:$versionPlaceholder "
                        cliInstallJarLatest += "${origin.groupId}:${origin.artifactId}:LATEST "
                    }
                }

                val loadCommand = "load_" + (origin.groupId + '_' + origin.artifactId)
                    .replace('-', '_')
                    .replace('.', '_')
                //language=graphql
                installRecipes += """
                  $loadCommand: installRecipesUniversal(
                    bundle: { maven: { groupId: "${origin.groupId}", artifactId: "${origin.artifactId}", version: "LATEST" } }
                  ) {
                    id
                  }"""

                val repoLink = "[${origin.groupId}:${origin.artifactId}](${origin.repositoryUrl})"
                val releaseLink = "[${origin.version}](${origin.releaseUrl(origin.version)})"
                writeln("| ${repoLink.padEnd(117)} | ${releaseLink.padEnd(90)} | ${origin.license.markdown()} |")
            }

            val pinnedInstalls = listOf(
                "jar" to cliInstallJarPinned,
                "pip" to cliInstallPipPinned,
                "npm" to cliInstallNpmPinned,
                "nuget" to cliInstallNugetPinned,
                "go" to cliInstallGoPinned,
            )
            val latestInstalls = listOf(
                "jar" to cliInstallJarLatest,
                "pip" to cliInstallPipLatest,
                "npm" to cliInstallNpmLatest,
                "nuget" to cliInstallNugetLatest,
                "go" to cliInstallGoLatest,
            )

            //language=markdown
            writeln(
                """

                ## CLI Installation

                Install the latest versions of all the OpenRewrite recipe modules into the Moderne CLI:

                <Tabs groupId="cliInstall">
                <TabItem value="pinned" label="Pinned versions">

                ```bash
                """.trimIndent()
            )
            for ((type, packages) in pinnedInstalls) {
                if (packages.isNotBlank()) writeln("mod config recipes $type install ${packages.trim()}")
            }
            writeln(
                """
                ```

                </TabItem>
                <TabItem value="latest" label="Latest versions">

                Install without a pinned version so you can later run `mod config recipes upgrade` to pull the newest versions without editing this command.

                ```bash
                """.trimIndent()
            )
            for ((type, packages) in latestInstalls) {
                if (packages.isNotBlank()) writeln("mod config recipes $type install ${packages.trim()}")
            }
            //language=markdown
            writeln(
                """
                ```

                </TabItem>
                </Tabs>

                ## Moderne Installation

                Install the latest versions of all the OpenRewrite [recipe modules into Moderne](https://docs.moderne.io/administrator-documentation/moderne-platform/how-to-guides/importing-external-recipes#importing-recipes-via-a-graphql-api-call) using the GraphQL endpoint.

                The mutation below uses `installRecipesUniversal`, which installs into the universal marketplace (visible to everyone) and requires the `admin` role.

                <details>
                <summary>
                Show GraphQL mutation.
                </summary>

                ```graphql
                mutation seedOpenRewriteArtifacts {
                ${installRecipes}
                }
                ```

                </details>

                ## Marketplace Sync

                As an alternative to installing modules one by one, the Moderne CLI can mirror an entire recipe marketplace into your local CLI.

                ### Option 1: Sync from app.moderne.io

                The default tenant is the free public Moderne instance at [app.moderne.io](https://app.moderne.io), which already publishes every OpenRewrite recipe artifact listed in the table above. Point the CLI at it (or any other Moderne tenant you have access to), log in, and sync:

                ```bash
                mod config moderne edit https://app.moderne.io
                mod config moderne login
                mod config recipes moderne sync
                ```

                ### Option 2: Import a self-hosted CSV

                If you cannot reach a Moderne tenant — for example in an air-gapped environment — you can supply your own CSV in the same [recipes-v5.csv format](https://docs.moderne.io/user-documentation/moderne-cli/references/recipes-csv/#csv-format) and import it directly:

                ```bash
                mod config recipes import csv path/to/recipes.csv
                ```

                Recipes with the same name are replaced by the imported version, so this can be re-run to refresh the marketplace. Pair it with the matching JAR/pip/npm/NuGet installs from [CLI Installation](#cli-installation) above so the recipes resolve when run.

                ### Additional sync details

                Under the hood, `mod config recipes moderne sync` picks one of two paths against the configured Moderne tenant:

                1. **Preferred — REST CSV (SaaS v2):** the CLI first tries `GET <apiHost>/api/recipes`. If the endpoint responds, the body is written to `~/.moderne/cli/recipes-v5.csv` and sync is done. The CSV has one row per recipe, with columns: `ecosystem`, `packageName`, `requestedVersion`, `version`, `name`, `displayName`, `description`, `recipeCount`, `category1`–`category6`, `category1Description`–`category6Description`, `options`, and `dataTables`. The CLI uses this catalog for search, tab completion, and MCP tooling. The same CSV is a good starting point for [Option 2](#option-2-import-a-self-hosted-csv): fetch it once from a tenant you have access to, then host or distribute it as the seed for `mod config recipes import csv` in environments that cannot reach Moderne directly.
                2. **Fallback — GraphQL + per-artifact install (SaaS v1):** if the REST endpoint is unavailable, the CLI issues a GraphQL query for every finished recipe deployment and installs each artifact from Maven, the same way `mod config recipes jar install` would:
                   ```graphql
                   query {
                     recipeDeployments(state: FINISHED) {
                       artifact {
                         groupId
                         artifactId
                         version
                         requestedVersion
                         datedSnapshotVersion
                       }
                     }
                   }
                   ```
                """.trimIndent()
            )
        }
    }

    fun createLatestVersionsJs(
        outputPath: Path,
        recipeOrigins: Collection<RecipeOrigin>,
        rewriteRecipeBomVersion: String,
        gradlePluginVersion: String,
        mavenPluginVersion: String
    ) {
        val versionsSnippetPath = outputPath.resolve("latest-versions.js")
        Files.newBufferedWriter(versionsSnippetPath, StandardOpenOption.CREATE).useAndApply {
            var recipeModuleVersions = ""
            for (origin in recipeOrigins) {
                recipeModuleVersions += "                  \"{{${origin.versionPlaceholderKey()}}}\": \"${origin.version}\",\n"
            }
            writeln(
                //language=ts
                """
                const latestVersions = {
                  "{{VERSION_REWRITE_RECIPE_BOM}}": "${rewriteRecipeBomVersion}",
                  "{{VERSION_REWRITE_GRADLE_PLUGIN}}": "${gradlePluginVersion}",
                  "{{VERSION_REWRITE_MAVEN_PLUGIN}}": "${mavenPluginVersion}",
                  ${recipeModuleVersions.trim()}
                };
                export default latestVersions;
                """.trimIndent()
            )
        }
    }
}
