name: Generate Latest Versions

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: 0 17 * * *

concurrency:
  group: "ci"
  cancel-in-progress: true

jobs:
  build:
    name: Generate Latest Versions
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4

      # Run generator
      - uses: actions/checkout@v4
      - name: Generate Markdown
        run: |
          ./gradlew ${{ env.GRADLE_SWITCHES }} run -Parg="--latest-versions-only"
          cat build/docs/latest-versions-of-every-openrewrite-module.md
